/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.18 codingold.gltf --transform 
Files: codingold.gltf [8.34MB] > C:\Users\Asus\Downloads\plugboard_-_ancient_coding\codingold-transformed.glb [187.04KB] (98%)
Author: museudocomputador (https://sketchfab.com/museudocomputador)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/plugboard-ancient-coding-b483e91712804a7bb387969c6d054870
Title: Plugboard - "Ancient" Coding
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/codingold-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Cube_1_Mat2_0.geometry} material={materials['Mat.2']} position={[-0.006, 0.009, 0.044]} scale={0.002} />
      <mesh geometry={nodes.Cube_1_Mat4_0.geometry} material={materials['Mat.4']} position={[-0.006, 0.009, 0.044]} scale={0.002} />
      <mesh geometry={nodes.Cube_1_Mat3_0.geometry} material={materials['Mat.3']} position={[-0.006, 0.009, 0.044]} scale={0.002} />
      <mesh geometry={nodes.Cube_1_Mat1_0.geometry} material={materials['Mat.1']} position={[-0.006, 0.009, 0.044]} scale={0.002} />
      <mesh geometry={nodes.Cube_1_Mat_0.geometry} material={materials.material} position={[-0.006, 0.009, 0.044]} scale={0.002} />
    </group>
  )
}

useGLTF.preload('/codingold-transformed.glb')
